import type { Metadata } from "next";
import { Ubuntu_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { cookies } from "next/headers";
import { AuthHydrator } from "./_components/auth-hydrator";
import ReactQueryProvider from "@/providers/react-query-provider";

const openSans = Open_Sans({
  variable: "--font-josefin-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 🔹 Auth Hydrator -> jembatani antara server dengan client
  const cookieStore = await cookies();
  const profileCookie = cookieStore.get("user_profile");
  const profile = profileCookie ? JSON.parse(profileCookie.value) : null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${ubuntuMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Hydrator */}
            <AuthHydrator profile={profile} />

            {/* Toast */}
            <Toaster />

            {/* Main */}
            {children}
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
